### PR TITLE
Roman changesv1

### PR DESCRIPTION
**Pull request by romannjoroge**
Added GRPC message config
Added posthog to monitor

### CODE REVIEW

**Comment by porkytheblack** [comment]
under review, will update this tuesday

**Comment by romannjoroge** [comment]
Sure that's fine. Do you want me to work on anything else in the mean time?

**Comment by porkytheblack** [comment]
We'll be starting work on convergence this week. 
After I'm done structuring everything, you'll pick at some pieces of it.

**Comment by romannjoroge** [comment]
Okay

**Comment by porkytheblack** [comment]
A couple of things to note. 
1. The GRPC server shouldn't be a separate app, it'll run as part of the reader because the store exists only on the reader, so that means it needs to be within the reader directory. Follow how I've defined the service for lagoon.
2. Stick with naming conventions from lagoon, don't change anything i.e how plugins are structured, how the data processors are structured etc. You defined your own structure within the grpc server plugins and data processors. The reason we need them to be similar is so that we can later switch them out with a library.
3. You didn't add the monitor catchers i.e setFailed for all the plugins under the indexer

The other parts are ok

**Comment by porkytheblack** [comment]
Additional note: always remember to push the lock file as well

and read this: https://www.conventionalcommits.org/en/v1.0.0/ for naming branches and commit messages

**Pull request merged**
